/**
 * Vision-based critique of a generated landing page.
 *
 * Sonnet 4.6 looks at the rendered page (first-fold + full-page
 * screenshots) and grades it like a senior conversion designer would —
 * "is the headline a clear value prop?", "does the CTA stand out?",
 * "is the offer above the fold?", "does it match the brand?". Returns
 * a structured critique with a 0-10 score, a pass/fail verdict against
 * a threshold, and a prioritised list of fixes the orchestrator can
 * feed back into the generator for the next iteration.
 *
 * The critique is the heart of the Manus-style build loop. Garbage in,
 * garbage iterations. The system prompt is heavy because the difference
 * between "good critique" and "useless critique" is whether the model
 * names specific sections + specific fixes vs. generic platitudes.
 */

import Anthropic from '@anthropic-ai/sdk'
import type { BrandAnalysis } from './brand-vision'
import type { CampaignIntake } from './vsl-generator'

const client = new Anthropic()
const MODEL = 'claude-sonnet-4-6'

export type IssueSeverity = 'minor' | 'major' | 'critical'

export interface CritiqueIssue {
  /** Section the issue lives in. Names should match the page-spec section
   *  types so the patcher can target precisely:
   *    "header" | "hero" | "problem" | "mechanism" | "proof" | "offer" |
   *    "guarantee" | "urgency" | "faq" | "cta" | "form" | "footer" |
   *    "global" (for whole-page issues like brand fidelity).
   */
  section: string
  severity: IssueSeverity
  /** What's wrong, in concrete terms. */
  problem: string
  /** Concrete actionable fix the patcher can apply. Imperative phrasing:
   *  "rewrite the hero headline as a benefit-focused statement of the
   *  dream outcome, max 9 words" — NOT "improve the headline". */
  fix_suggestion: string
}

export interface PageCritique {
  /** 0-10 overall quality score. 10 = ship-ready, 0 = fundamentally broken. */
  score: number
  /** True iff score >= the threshold the orchestrator passed in. The
   *  orchestrator sets the bar; the model just reports the score. */
  pass: boolean
  /** One-paragraph plain-English summary the operator sees in the
   *  iteration timeline. Don't repeat the issues — describe the page. */
  summary: string
  issues: CritiqueIssue[]
  /** What's working — surfaced so we don't accidentally regress these
   *  in the next iteration. Fed back into the patcher prompt as
   *  "preserve these qualities". */
  strengths: string[]
}

const SYSTEM_PROMPT = `You are a senior conversion designer reviewing a landing page that was just generated by an AI for a specific direct-response offer. Your critique drives the next regeneration pass — be specific, concrete, and prioritised.

You will see two screenshots:
1. FIRST-FOLD (1440x900) — what visitors see before scrolling. Most important.
2. FULL-PAGE — the entire scroll, top to bottom. Reveals layout flow, section ordering, mobile-unfriendly density, etc.

You will also see the campaign intake (what the page is supposed to do), the brand analysis (what on-brand looks like for this operator), and — if this is iteration 2+ — the previous critique, so you can verify whether prior issues were actually fixed.

Grade the page on these dimensions:

A. CLARITY (3 points)
   - Within 5 seconds of seeing the first-fold, does a stranger understand WHO it's for, WHAT they get, and WHY they should care?
   - Headline is a benefit-focused value prop, not a feature list, not a clever pun
   - Sub-headline reinforces the dream outcome with specifics
   - One unambiguous primary CTA, visually dominant

B. BRAND FIDELITY (2 points)
   - Colours match the brand_analysis primary + accents — not generic blue/grey
   - Typography matches the typography_style (serif/sans/display)
   - Photography matches photography_style — illustrated brand should NOT have stock-photo hero
   - Overall vibe matches design_vibe (e.g. "warm minimalist" should not look "corporate dense")

C. PERSUASION ARCHITECTURE (3 points)
   - Hero → Problem → Mechanism → Proof → Offer → Guarantee → CTA flow is intact
   - Proof is concrete (testimonials with names, metrics with numbers) — not generic
   - Offer is clear with explicit deliverables and price (or a clear path to price)
   - Guarantee de-risks the buyer
   - Multiple CTAs throughout, all pointing to the same form/action

D. EXECUTION QUALITY (2 points)
   - No broken images (placeholders, 404s, generic stock that screams AI)
   - Spacing/whitespace is generous, not cramped or chaotic
   - No console errors or 4xx/5xx network requests (these are critical bugs)
   - Layout works at desktop width — sections are full-width or properly contained
   - Copy has no AI tells: no "Imagine if...", no "Are you tired of...", no "In today's world..."

Score = sum of awarded points across A-D, rounded to one decimal. 10.0 is exceptional; 8.0 is ship-ready; below 6.0 is fundamentally broken.

ISSUES — list the most impactful problems first. For each:
- "section": which section it lives in (use spec types: hero, problem, mechanism, proof, offer, guarantee, urgency, faq, cta, form, footer, header, or "global" for whole-page concerns)
- "severity": "critical" (blocks shipping — broken layout, runtime error, off-brand colour scheme), "major" (hurts conversion — weak headline, missing proof, generic copy), "minor" (polish — wording tweaks, spacing nitpicks)
- "problem": one sentence, concrete
- "fix_suggestion": IMPERATIVE phrasing telling the next regeneration EXACTLY what to do. "Rewrite the hero headline as a benefit-focused statement of the dream outcome, max 9 words." NOT "improve the headline."

If you list more than 8 issues, you are being noisy. Pick the 4-6 that will actually move the score.

STRENGTHS — what's working that we MUST preserve in the next iteration. 2-4 items.

If the previous iteration's critique is provided, evaluate each prior issue: was it fixed? If not, list it again (severity may have changed). If yes, mention it in strengths.

Return everything via the page_critique tool. Be honest — flattering critiques produce mediocre pages.`

const TOOL_SCHEMA = {
  type: 'object' as const,
  required: ['score', 'pass', 'summary', 'issues', 'strengths'],
  properties: {
    score: { type: 'number', minimum: 0, maximum: 10 },
    pass: { type: 'boolean' },
    summary: { type: 'string', maxLength: 600 },
    issues: {
      type: 'array',
      maxItems: 12,
      items: {
        type: 'object',
        required: ['section', 'severity', 'problem', 'fix_suggestion'],
        properties: {
          section: { type: 'string', maxLength: 30 },
          severity: { type: 'string', enum: ['minor', 'major', 'critical'] },
          problem: { type: 'string', maxLength: 280 },
          fix_suggestion: { type: 'string', maxLength: 400 },
        },
      },
    },
    strengths: { type: 'array', items: { type: 'string', maxLength: 200 }, maxItems: 6 },
  },
}

export async function critiqueLandingPage(args: {
  firstFoldBase64: string
  fullPageBase64: string
  screenshotMime: 'image/png' | 'image/jpeg'
  intake: CampaignIntake
  primaryColor: string
  brandAnalysis?: BrandAnalysis | null
  /** Reference site screenshot URL (if the operator provided a reference
   *  URL and it was scraped). Helps the model judge brand fidelity by
   *  visual comparison rather than just from the analysis text. */
  brandReferenceScreenshotUrl?: string | null
  /** Console + network errors observed during render — fed in directly
   *  so the model doesn't have to guess from pixels. */
  consoleErrors?: string[]
  networkErrors?: Array<{ url: string; status: number }>
  /** 1-indexed iteration this critique is for. Iteration 1 has no
   *  previous critique. */
  iterationNumber: number
  previousCritique?: PageCritique | null
  /** Threshold the orchestrator wants the page to clear. Used by the
   *  model only as the explicit pass/fail bar — it still scores 0-10. */
  scoreThreshold: number
}): Promise<PageCritique> {
  const intakeBits = [
    `Business: ${args.intake.business_name}`,
    `Offer: ${args.intake.offer}`,
    `Dream outcome the page must promise: ${args.intake.dream_outcome}`,
    args.intake.false_belief ? `False belief to break: ${args.intake.false_belief}` : '',
    args.intake.mechanism ? `Unique mechanism: ${args.intake.mechanism}` : '',
    args.intake.proof ? `Proof available: ${args.intake.proof}` : '',
    args.intake.price ? `Price point: ${args.intake.price}` : '',
    args.intake.audience ? `Audience: ${args.intake.audience}` : '',
    args.intake.industry ? `Industry: ${args.intake.industry}` : '',
    `Brand voice: ${args.intake.brand_voice ?? 'friendly'}`,
    `Primary brand colour (operator-picked): ${args.primaryColor}`,
  ].filter(Boolean).join('\n')

  const brandBits: string[] = []
  if (args.brandAnalysis) {
    const a = args.brandAnalysis
    brandBits.push(
      `Brand identity (extracted from operator's existing site):`,
      `- design vibe: ${a.design_vibe || 'unknown'}`,
      `- typography: ${a.typography_style} (${a.typography_descriptor || ''})`,
      `- photography style: ${a.photography_style}`,
      `- voice tone: ${a.voice_tone}`,
      `- visual motifs: ${(a.visual_motifs ?? []).join(', ') || '—'}`,
      `- accent colours: ${(a.accent_colors ?? []).join(', ') || '—'}`,
    )
  }

  const errorBits: string[] = []
  if (args.consoleErrors && args.consoleErrors.length > 0) {
    errorBits.push(`Console errors observed during render:\n${args.consoleErrors.slice(0, 10).map((e) => `• ${e}`).join('\n')}`)
  }
  if (args.networkErrors && args.networkErrors.length > 0) {
    errorBits.push(`Failed network requests:\n${args.networkErrors.slice(0, 10).map((e) => `• ${e.status} ${e.url}`).join('\n')}`)
  }

  const previousBits: string[] = []
  if (args.iterationNumber > 1 && args.previousCritique) {
    previousBits.push(
      `Previous iteration (iteration ${args.iterationNumber - 1}) scored ${args.previousCritique.score.toFixed(1)} / 10.`,
      `Previous summary: ${args.previousCritique.summary}`,
      `Previous issues that the patcher attempted to fix:`,
      ...args.previousCritique.issues.map((i) => `• [${i.severity}] ${i.section}: ${i.problem} → fix attempted: ${i.fix_suggestion}`),
    )
  }

  const userText = [
    `This is iteration ${args.iterationNumber}. Pass threshold: ${args.scoreThreshold}/10.`,
    '',
    'CAMPAIGN INTAKE:',
    intakeBits,
    brandBits.length > 0 ? `\n${brandBits.join('\n')}` : '',
    errorBits.length > 0 ? `\n${errorBits.join('\n\n')}` : '',
    previousBits.length > 0 ? `\n${previousBits.join('\n')}` : '',
    '',
    'Critique the page. The first image is the first-fold. The second is the full-page scroll.',
  ].filter(Boolean).join('\n')

  const userContent: Anthropic.ContentBlockParam[] = [
    { type: 'image', source: { type: 'base64', media_type: args.screenshotMime, data: args.firstFoldBase64 } },
    { type: 'image', source: { type: 'base64', media_type: args.screenshotMime, data: args.fullPageBase64 } },
  ]
  if (args.brandReferenceScreenshotUrl) {
    userContent.push({ type: 'image', source: { type: 'url', url: args.brandReferenceScreenshotUrl } })
    userContent.push({ type: 'text', text: 'The third image (above) is the operator\'s existing brand site — judge brand fidelity by direct visual comparison.' })
  }
  userContent.push({ type: 'text', text: userText })

  const response = await client.messages.create({
    model: MODEL,
    max_tokens: 4000,
    system: [{ type: 'text', text: SYSTEM_PROMPT, cache_control: { type: 'ephemeral' } }],
    tools: [{
      name: 'page_critique',
      description: 'Return the structured critique of the rendered landing page.',
      input_schema: TOOL_SCHEMA,
    }],
    tool_choice: { type: 'tool', name: 'page_critique' },
    messages: [{ role: 'user', content: userContent }],
  })

  let raw: Record<string, unknown> | null = null
  for (const block of response.content) {
    if (block.type === 'tool_use' && block.name === 'page_critique') {
      raw = block.input as Record<string, unknown>
      break
    }
  }
  if (!raw) {
    throw new Error(`Critic returned no critique (stop_reason=${response.stop_reason ?? 'unknown'})`)
  }

  return normalise(raw, args.scoreThreshold)
}

function normalise(raw: Record<string, unknown>, threshold: number): PageCritique {
  const score = clampNum(raw.score, 0, 10, 0)
  const issues: CritiqueIssue[] = Array.isArray(raw.issues)
    ? (raw.issues as unknown[]).flatMap((i) => {
        if (!i || typeof i !== 'object') return []
        const o = i as Record<string, unknown>
        const severity = enumOr(o.severity, ['minor', 'major', 'critical'] as const, 'major')
        const section = typeof o.section === 'string' && o.section.trim() ? o.section.trim().slice(0, 30) : 'global'
        const problem = typeof o.problem === 'string' ? o.problem.slice(0, 280) : ''
        const fix = typeof o.fix_suggestion === 'string' ? o.fix_suggestion.slice(0, 400) : ''
        if (!problem || !fix) return []
        return [{ section, severity, problem, fix_suggestion: fix }]
      }).slice(0, 12)
    : []
  return {
    score,
    pass: score >= threshold,
    summary: typeof raw.summary === 'string' ? raw.summary.slice(0, 600) : '',
    issues,
    strengths: Array.isArray(raw.strengths)
      ? (raw.strengths as unknown[]).filter((s): s is string => typeof s === 'string' && !!s).slice(0, 6)
      : [],
  }
}

function clampNum(v: unknown, min: number, max: number, fallback: number): number {
  if (typeof v !== 'number' || !Number.isFinite(v)) return fallback
  return Math.max(min, Math.min(max, v))
}

function enumOr<T extends string>(v: unknown, allowed: readonly T[], fallback: T): T {
  if (typeof v === 'string' && (allowed as readonly string[]).includes(v)) return v as T
  return fallback
}
